debug: true

build:
  when:
    event: tag
  image: firecyberice/rpi-docker:1.10.0-dev
  environment:
    - DOCKER_HOST=tcp://localhost:2375
  commands:
    - apk update && apk add curl tar gzip
    - export VERSION=$$TAG
#    - curl --silent https://raw.githubusercontent.com/docker/docker/master/contrib/mkimage-alpine.sh > mkimage-alpine.sh
    - chmod +x mkimage-alpine.sh
    - ./mkimage-alpine.sh -s -r ${VERSION}
    - ls -la

compose:
  docker:
    privileged: true
    image: firecyberice/rpi-docker:1.10.0-dev-dind

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: sercand/armhf-alpine
    tag:
      - $$TAG
    when:
      event: tag
